### ISSUE TITLE
상품 생성

### ISSUE THREAD

**Issue by devksh930** [f-lab-edu/special-price-shop#3]
# Summary
래플 상품과 타임딜 상품을 생성한다.
# TO-DO
- [x] 래플과 타임딜 엔티티 생성
- [x] 래플 상품 등록
- [x] 타임딜 상품 등록
